// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/article.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Model `Enumerations`
type Article_StatusType int32

const (
	Article_DRAFT       Article_StatusType = 0
	Article_PUBLISHED   Article_StatusType = 1
	Article_UNPUBLISHED Article_StatusType = 2
)

var Article_StatusType_name = map[int32]string{
	0: "DRAFT",
	1: "PUBLISHED",
	2: "UNPUBLISHED",
}

var Article_StatusType_value = map[string]int32{
	"DRAFT":       0,
	"PUBLISHED":   1,
	"UNPUBLISHED": 2,
}

func (x Article_StatusType) String() string {
	return proto.EnumName(Article_StatusType_name, int32(x))
}

func (Article_StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fb85c0ea4e218a5a, []int{0, 0}
}

type Article struct {
	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// Implement Enumerations
	Status Article_StatusType `protobuf:"varint,4,opt,name=status,proto3,enum=pb.Article_StatusType" json:"status,omitempty"`
	// Implement Array Value
	Tags []*Article_Tags `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// Impelemnt Maps
	SocialMediaStatistic map[string]*Article_SocialMediaStatisticField `protobuf:"bytes,6,rep,name=SocialMediaStatistic,proto3" json:"SocialMediaStatistic,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Model `Oneof`
	//
	// Types that are valid to be assigned to ProcessOneof:
	//	*Article_Insert
	//	*Article_Update
	//	*Article_Delete
	//	*Article_Archive
	ProcessOneof         isArticle_ProcessOneof `protobuf_oneof:"process_oneof"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb85c0ea4e218a5a, []int{0}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Article) GetStatus() Article_StatusType {
	if m != nil {
		return m.Status
	}
	return Article_DRAFT
}

func (m *Article) GetTags() []*Article_Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Article) GetSocialMediaStatistic() map[string]*Article_SocialMediaStatisticField {
	if m != nil {
		return m.SocialMediaStatistic
	}
	return nil
}

type isArticle_ProcessOneof interface {
	isArticle_ProcessOneof()
}

type Article_Insert struct {
	Insert bool `protobuf:"varint,7,opt,name=insert,proto3,oneof"`
}

type Article_Update struct {
	Update bool `protobuf:"varint,8,opt,name=update,proto3,oneof"`
}

type Article_Delete struct {
	Delete bool `protobuf:"varint,9,opt,name=delete,proto3,oneof"`
}

type Article_Archive struct {
	Archive bool `protobuf:"varint,10,opt,name=archive,proto3,oneof"`
}

func (*Article_Insert) isArticle_ProcessOneof() {}

func (*Article_Update) isArticle_ProcessOneof() {}

func (*Article_Delete) isArticle_ProcessOneof() {}

func (*Article_Archive) isArticle_ProcessOneof() {}

func (m *Article) GetProcessOneof() isArticle_ProcessOneof {
	if m != nil {
		return m.ProcessOneof
	}
	return nil
}

func (m *Article) GetInsert() bool {
	if x, ok := m.GetProcessOneof().(*Article_Insert); ok {
		return x.Insert
	}
	return false
}

func (m *Article) GetUpdate() bool {
	if x, ok := m.GetProcessOneof().(*Article_Update); ok {
		return x.Update
	}
	return false
}

func (m *Article) GetDelete() bool {
	if x, ok := m.GetProcessOneof().(*Article_Delete); ok {
		return x.Delete
	}
	return false
}

func (m *Article) GetArchive() bool {
	if x, ok := m.GetProcessOneof().(*Article_Archive); ok {
		return x.Archive
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Article) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Article_Insert)(nil),
		(*Article_Update)(nil),
		(*Article_Delete)(nil),
		(*Article_Archive)(nil),
	}
}

// Untuk model `Repeated`
type Article_Tags struct {
	TagId                int32    `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article_Tags) Reset()         { *m = Article_Tags{} }
func (m *Article_Tags) String() string { return proto.CompactTextString(m) }
func (*Article_Tags) ProtoMessage()    {}
func (*Article_Tags) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb85c0ea4e218a5a, []int{0, 0}
}

func (m *Article_Tags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article_Tags.Unmarshal(m, b)
}
func (m *Article_Tags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article_Tags.Marshal(b, m, deterministic)
}
func (m *Article_Tags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article_Tags.Merge(m, src)
}
func (m *Article_Tags) XXX_Size() int {
	return xxx_messageInfo_Article_Tags.Size(m)
}
func (m *Article_Tags) XXX_DiscardUnknown() {
	xxx_messageInfo_Article_Tags.DiscardUnknown(m)
}

var xxx_messageInfo_Article_Tags proto.InternalMessageInfo

func (m *Article_Tags) GetTagId() int32 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *Article_Tags) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Untuk model `Map`
type Article_SocialMediaStatisticField struct {
	Like                 int32    `protobuf:"varint,1,opt,name=Like,proto3" json:"Like,omitempty"`
	Share                int32    `protobuf:"varint,2,opt,name=Share,proto3" json:"Share,omitempty"`
	Comments             int32    `protobuf:"varint,3,opt,name=Comments,proto3" json:"Comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article_SocialMediaStatisticField) Reset()         { *m = Article_SocialMediaStatisticField{} }
func (m *Article_SocialMediaStatisticField) String() string { return proto.CompactTextString(m) }
func (*Article_SocialMediaStatisticField) ProtoMessage()    {}
func (*Article_SocialMediaStatisticField) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb85c0ea4e218a5a, []int{0, 1}
}

func (m *Article_SocialMediaStatisticField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article_SocialMediaStatisticField.Unmarshal(m, b)
}
func (m *Article_SocialMediaStatisticField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article_SocialMediaStatisticField.Marshal(b, m, deterministic)
}
func (m *Article_SocialMediaStatisticField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article_SocialMediaStatisticField.Merge(m, src)
}
func (m *Article_SocialMediaStatisticField) XXX_Size() int {
	return xxx_messageInfo_Article_SocialMediaStatisticField.Size(m)
}
func (m *Article_SocialMediaStatisticField) XXX_DiscardUnknown() {
	xxx_messageInfo_Article_SocialMediaStatisticField.DiscardUnknown(m)
}

var xxx_messageInfo_Article_SocialMediaStatisticField proto.InternalMessageInfo

func (m *Article_SocialMediaStatisticField) GetLike() int32 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *Article_SocialMediaStatisticField) GetShare() int32 {
	if m != nil {
		return m.Share
	}
	return 0
}

func (m *Article_SocialMediaStatisticField) GetComments() int32 {
	if m != nil {
		return m.Comments
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.Article_StatusType", Article_StatusType_name, Article_StatusType_value)
	proto.RegisterType((*Article)(nil), "pb.Article")
	proto.RegisterMapType((map[string]*Article_SocialMediaStatisticField)(nil), "pb.Article.SocialMediaStatisticEntry")
	proto.RegisterType((*Article_Tags)(nil), "pb.Article.Tags")
	proto.RegisterType((*Article_SocialMediaStatisticField)(nil), "pb.Article.SocialMediaStatisticField")
}

func init() { proto.RegisterFile("pb/article.proto", fileDescriptor_fb85c0ea4e218a5a) }

var fileDescriptor_fb85c0ea4e218a5a = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4e, 0xdb, 0x40,
	0x10, 0xc5, 0x4e, 0xec, 0xc4, 0x83, 0x00, 0x6b, 0x44, 0xab, 0xad, 0x4f, 0x16, 0x6a, 0x25, 0x9f,
	0x5c, 0x95, 0x1e, 0x5a, 0xb5, 0x27, 0x28, 0x20, 0x90, 0x68, 0x55, 0x6d, 0xc2, 0xa1, 0x27, 0xb4,
	0xb1, 0xa7, 0x61, 0x85, 0x63, 0x5b, 0xde, 0x09, 0x52, 0xfe, 0xab, 0x1f, 0x58, 0x79, 0x6d, 0x93,
	0x56, 0xca, 0x81, 0xdb, 0xbc, 0x79, 0x33, 0xef, 0xed, 0xbe, 0x5d, 0x08, 0xeb, 0xc5, 0x7b, 0xd5,
	0xb0, 0xce, 0x0a, 0x4a, 0xeb, 0xa6, 0xe2, 0x0a, 0xdd, 0x7a, 0x71, 0xf2, 0xc7, 0x83, 0xc9, 0x59,
	0xd7, 0xc5, 0x43, 0x70, 0x75, 0x2e, 0x9c, 0xd8, 0x49, 0x3c, 0xe9, 0xea, 0x1c, 0x8f, 0xc1, 0x63,
	0xcd, 0x05, 0x09, 0x37, 0x76, 0x92, 0x40, 0x76, 0x00, 0x05, 0x4c, 0xb2, 0xaa, 0x64, 0x2a, 0x59,
	0x8c, 0x6c, 0x7f, 0x80, 0x98, 0x82, 0x6f, 0x58, 0xf1, 0xda, 0x88, 0x71, 0xec, 0x24, 0x87, 0xa7,
	0xaf, 0xd3, 0x7a, 0x91, 0xf6, 0xe2, 0xe9, 0xcc, 0x32, 0xf3, 0x4d, 0x4d, 0xb2, 0x9f, 0xc2, 0xb7,
	0x30, 0x66, 0xb5, 0x34, 0xc2, 0x8b, 0x47, 0xc9, 0xfe, 0x69, 0xf8, 0xef, 0xf4, 0x5c, 0x2d, 0x8d,
	0xb4, 0x2c, 0xfe, 0x82, 0xe3, 0x59, 0x95, 0x69, 0x55, 0x7c, 0xa7, 0x5c, 0xab, 0x56, 0x46, 0x1b,
	0xd6, 0x99, 0xf0, 0xed, 0xd6, 0xbb, 0xff, 0x3c, 0x76, 0xcc, 0x5d, 0x96, 0xdc, 0x6c, 0xe4, 0x4e,
	0x09, 0x14, 0xe0, 0xeb, 0xd2, 0x50, 0xc3, 0x62, 0x12, 0x3b, 0xc9, 0xf4, 0x7a, 0x4f, 0xf6, 0xb8,
	0x65, 0xd6, 0x75, 0xae, 0x98, 0xc4, 0x74, 0x60, 0x3a, 0xdc, 0x32, 0x39, 0x15, 0xc4, 0x24, 0x82,
	0x81, 0xe9, 0x30, 0x46, 0x30, 0x51, 0x4d, 0xf6, 0xa0, 0x9f, 0x48, 0x40, 0x4f, 0x0d, 0x8d, 0xe8,
	0x03, 0x8c, 0xdb, 0x2b, 0xe1, 0x2b, 0xf0, 0x59, 0x2d, 0xef, 0x9f, 0x63, 0xf6, 0x58, 0x2d, 0x6f,
	0x72, 0x44, 0x18, 0x97, 0x6a, 0x35, 0x04, 0x6d, 0xeb, 0x48, 0xc1, 0x9b, 0x5d, 0x87, 0xbe, 0xd2,
	0x54, 0xd8, 0x85, 0x5b, 0xfd, 0x48, 0xbd, 0x8a, 0xad, 0xdb, 0xe7, 0x9a, 0x3d, 0xa8, 0xa6, 0x53,
	0xf1, 0x64, 0x07, 0x30, 0x82, 0xe9, 0xb7, 0x6a, 0xb5, 0xa2, 0x92, 0x8d, 0x7d, 0x2f, 0x4f, 0x3e,
	0xe3, 0xa8, 0xdc, 0x6d, 0x61, 0x23, 0xc3, 0x10, 0x46, 0x8f, 0xb4, 0xb1, 0x0e, 0x81, 0x6c, 0x4b,
	0xfc, 0x0a, 0xde, 0x93, 0x2a, 0xd6, 0x9d, 0xc1, 0x0b, 0xa2, 0xb7, 0x47, 0x95, 0xdd, 0xce, 0x17,
	0xf7, 0xb3, 0x73, 0xf2, 0x09, 0x60, 0xfb, 0x0d, 0x30, 0x00, 0xef, 0x42, 0x9e, 0x5d, 0xcd, 0xc3,
	0x3d, 0x3c, 0x80, 0xe0, 0xe7, 0xdd, 0xf9, 0xed, 0xcd, 0xec, 0xfa, 0xf2, 0x22, 0x74, 0xf0, 0x08,
	0xf6, 0xef, 0x7e, 0x6c, 0x1b, 0xee, 0xf9, 0x11, 0x1c, 0xd4, 0x4d, 0x95, 0x91, 0x31, 0xf7, 0x55,
	0x49, 0xd5, 0xef, 0x85, 0x6f, 0x7f, 0xf0, 0xc7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x08,
	0xaf, 0xd6, 0xd5, 0x02, 0x00, 0x00,
}
